### ISSUE TITLE
The Breeze wiki contents(temporary)

### ISSUE THREAD

**Issue by maksyuki** [myyerrol/myyerrol_website_development#2]
breeze的wiki组织形式

- Breeze mini四轴飞行器(*)：总纲
- Breeze mini四轴飞行器(*)：入手组装和调试指导
- Breeze mini四轴飞行器(*)：硬件电路设计

    - 硬件选型

    - 电路原理图
    - PCB布局与布线
- Breeze mini四轴飞行器(*)：机械结构设计
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-开发环境搭建(Keil)
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-开发环境搭建(ARM-GCC)
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-Makefile详解(ARM-GCC)
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-链接脚本详解(ARM-GCC)
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-启动文件详解(ARM-GCC)
- Breeze mini四轴飞行器(*)：STM32嵌入式开发-代码编写规范
- Breeze mini四轴飞行器(*)：飞控算法总览
- Breeze mini四轴飞行器(*)：STM32系统开发- 启动文件与CMSIS
- Breeze mini四轴飞行器(*)：STM32系统开发-固件库与固件库编程
- Breeze mini四轴飞行器(*)：STM32驱动开发-系统时钟树
- Breeze mini四轴飞行器(*)：STM32驱动开发-内存和管脚映射
- Breeze mini四轴飞行器(*)：STM32驱动开发-中断向量控制
- Breeze mini四轴飞行器(*)：STM32驱动开发-IIC和USART
- Breeze mini四轴飞行器(*)：STM32驱动开发-高级定时器
- Breeze mini四轴飞行器(*)：STM32驱动开发-读写Flash和模拟EEPROM
- Breeze mini四轴飞行器(*)：STM32模块开发-LED
- Breeze mini四轴飞行器(*)：STM32模块开发-PWM
- Breeze mini四轴飞行器(*)：STM32模块开发-MS5611
- Breeze mini四轴飞行器(*)：STM32模块开发-MPU6050
- Breeze mini四轴飞行器(*)：STM32模块开发-MPU6050硬件解算
- Breeze mini四轴飞行器(*)：nRF51822开发环境搭建(Keil)
- Breeze mini四轴飞行器(*)：nRF51822开发-蓝牙简介
- Breeze mini四轴飞行器(*)：nRF51822开发-蓝牙协议栈与应用编程
- Breeze mini四轴飞行器(*)：nRF51822开发-ADC和电池管理
- Breeze mini四轴飞行器(*)：nRF51822开发-蓝牙串口透传
- Breeze mini四轴飞行器(*)：通信协议详解
- Breeze mini四轴飞行器(*)：PC，IOS和Android上位机介绍
- Breeze mini四轴飞行器(*)：飞控算法理论与设计

    - 基础知识

        - 四轴飞行器基本结构及飞行原理

            - 坐标系定义

            - 飞行原理

        - 四轴飞行器飞行姿态表示

            - 欧拉角

            - 四元数

        - 四轴飞行器动力学模型建立方法

            - 机理建模法

            - 辨识建模法

    - 姿态数据滤波

        - 传感器数据读取与分析

        - 数字滤波器设计

            - 常用数字滤波器与IIR滤波器简介

            - 使用Matlab辅助设计IIR滤波器设计

    - 姿态解算

        - 互补滤波

        - 卡尔曼滤波

        - 四元数引入

    - 最小二乘辨识得到系统动力学模型(被控对象)

        - 辨识目的和先验知识

        - 实验设计

        - 模型结构辨识

        - 模型参数辨识

    - 串联PID控制算法设计与整定
        - Matlab仿真

        - 真机调试

    - 高度串联PID控制算法与整定
        - Matlab仿真

        - 真机调试

    - 总体调试与经验总结
- Breeze系列四轴飞行器(*)：知识库——四轴飞行器介绍

    - 四轴飞行器历史回顾和介绍

    - 商业四轴飞行器和开源四轴飞行器

    - 大四轴VS小四轴

    - 发展前景和研究现状
- Breeze系列四轴飞行器(*)：知识库——

    - 电机

        - 无刷直流和有刷直流电机

    - 桨叶

    - 电池

**Comment by myyerrol** [comment]
I think your suggestion is very great!
